In [6]:
import lxml.html as lh
from time import sleep
import pandas as pd
import numpy as np
import requests
import bs4
from bs4 import BeautifulSoup

In [7]:
def stock_data():
    r = requests.get("https://www.moneycontrol.com/stocks/marketstats/indexcomp.php?optex=NSE&opttopic=indexcomp&index=9")
    soup = BeautifulSoup(r.text, 'html.parser')
    
    doc = lh.fromstring(r.content)
    tr_elements = doc.xpath('//tr')
    
    col=[]
    i=0
    for t in tr_elements[1]:
        i+=1
        name=t.text_content()
        #print('%d:"%s"'%(i,name))
        col.append((name,[]))
    
    col[0] = ('Company Name', [])

    #Since out first row is the header, data is stored on the second row onwards
    for j in range(1,len(tr_elements)):
        #T is our j'th row
        T=tr_elements[j]

        #If row is not of size 6, the //tr data is not from our table 
        if len(T)!=6:
            break

        #i is the index of our column
        i=0

        #Iterate through each element of the row
        for t in T.iterchildren():
            data=t.text_content() 

            #Check if row is empty
            if i>0:
            #Convert any numerical value to integers
                try:
                    data=int(data)
                except:
                    pass
            
            #Append the data to the empty list of the i'th column
            col[i][1].append(data)
            #Increment i for the next column
            i+=1
            
    Dict={title:column for (title,column) in col}
    df=pd.DataFrame(Dict)
    df = df.drop(df.index[[0]])
    return df

In [139]:
data = stock_data()
data.head(10)

,Company Name,Industry,LastPrice,Change,%Chg,Mkt Cap(Rs cr)
1,Adani Ports\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\...,Transport Infrastructure,229.90,22.10,10.64,"46,709.97"
2,Asian Paints\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t...,Paints,"1,558.05",59.60,3.98,"149,447.81"
3,Axis Bank\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\...,Bank - Private,300.90,-7.75,-2.51,"84,897.17"
4,Bajaj Auto\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t...,Automobile - 2 & 3 Wheelers,"1,898.45",-37.10,-1.92,"54,934.88"
5,Bajaj Finance\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\...,Finance - NBFC,"2,381.55",115.40,5.09,"143,295.26"
6,Bajaj Finserv\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\...,Finance - Investment,"4,475.00",-146.05,-3.16,"71,213.94"
7,Bharti Airtel\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\...,Telecommunication - Service Provider,416.55,9.20,2.26,"227,251.24"
8,Bharti Infratel\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\...,Telecommunication - Equipment,138.55,-4.85,-3.38,"25,626.32"
9,BPCL\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t...,Refineries,263.90,-5.45,-2.02,"57,246.58"
10,Britannia\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\...,Consumer Food,"2,422.40",284.55,13.31,"58,251.04"

In [8]:
#function to print the data scraped from the website every 30 seconds for the next 'x' minutes
def print_stock_data(x):

    flag = True
    counter = 0
    refreshRate = 30
    
    while flag:
        print("===========================================================\n")
        print(stock_data())
        sleep(refreshRate)
        counter +=1
        if (counter == (x*2)):
            flag = False

In [81]:
#for 20 minutes, call print_stock_data(20)
print_stock_data(1)

================================================================

=========================================================

                                         Company Name  \
1   Adani Ports\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\...
2   Asian Paints\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t...
3   Axis Bank\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\...
4   Bajaj Auto\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t...
5   Bajaj Finance\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\...
6   Bajaj Finserv\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\...
7   Bharti Airtel\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\...
8   Bharti Infratel\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\...
9   BPCL\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t...
10  Britannia\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\...
11  Cipla\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\...
12  Coal India\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t...
13  Dr Reddys Labs\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t...
14  Eicher Motors\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\...
15  GAIL\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t...
16  Grasim\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t...
17  HCL Tech\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t...
18  HDFC\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t...
19  HDFC Bank\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\...
20  Hero Motocorp\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\...
21  Hindalco\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t...
22  HUL\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\...
23  ICICI Bank\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t...
24  IndusInd Bank\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\...
25  Infosys\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\...
26  IOC\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\...
27  ITC\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\...
28  JSW Steel\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\...
29  Kotak Mahindra\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t...
30  Larsen\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t...
31  M&M\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\...
32  Maruti Suzuki\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\...
33  Nestle\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t...
34  NTPC\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t...
35  ONGC\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t...
36  Power Grid Corp\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\...
37  Reliance\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t...
38  SBI\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\...
39  Sun Pharma\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t...
40  Tata Motors\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\...
41  Tata Steel\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t...
42  TCS\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\...
43  Tech Mahindra\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\...
44  Titan Company\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\...
45  UltraTechCement\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\...
46  UPL\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\...
47  Vedanta\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\...
48  Wipro\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\...
49  Yes Bank\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t...
50  Zee Entertain\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\...

                                   Industry  LastPrice     Change    %Chg  \
1                  Transport Infrastructure     207.80     -48.60  -18.95
2                                    Paints   1,498.45    -244.50  -14.03
3                            Bank - Private     308.65    -119.50  -27.91
4               Automobile - 2 & 3 Wheelers   1,935.55    -306.75  -13.68
5                            Finance - NBFC   2,266.15    -685.75  -23.23
6                      Finance - Investment   4,621.05  -1,612.00  -25.86
7      Telecommunication - Service Provider     407.35     -55.30  -11.95
8             Telecommunication - Equipment     143.40      -4.75   -3.21
9                                Refineries     269.35     -48.50  -15.26
10                            Consumer Food   2,137.85    -329.95  -13.37
11                  Pharmaceuticals & Drugs     375.25     -17.55   -4.47
12                                     Coal     127.85      -4.95   -3.73
13                  Pharmaceuticals & Drugs   2,768.40    -128.85   -4.45
14                  Automobile - LCVS/ HVCS  13,705.90  -1,972.55  -12.58
15                         Gas Distribution      78.00      -2.80   -3.47
16                              Diversified     433.25     -96.15  -18.16
17                 IT Services & Consulting     417.15     -27.75   -6.24
18                        Finance - Housing   1,520.70    -233.25  -13.30
19                           Bank - Private     771.55    -111.30  -12.61
20              Automobile - 2 & 3 Wheelers   1,616.00    -199.70  -11.00
21                             Iron & Steel      87.90     -17.60  -16.68
22            Household & Personal Products   1,869.70    -182.00   -8.87
23                           Bank - Private     284.00     -61.70  -17.85
24                           Bank - Private     336.45    -103.90  -23.59
25                 IT Services & Consulting     526.45     -58.75  -10.04
26                               Refineries      80.75      -9.85  -10.87
27                       Cigarettes/Tobacco     154.30     -21.20  -12.08
28                             Iron & Steel     144.40     -31.35  -17.84
29                           Bank - Private   1,098.25    -164.10  -13.00
30               Engineering & Construction     724.05    -140.65  -16.27
31  Automobile - Auto & Truck Manufacturers     293.40     -29.20   -9.05
32              Automobile - Passenger Cars   4,220.35    -858.85  -16.91
33                            Consumer Food  12,944.65  -1,200.85   -8.49
34            Power Generation/Distribution      76.40      -4.85   -5.97
35           Oil Exploration and Production      60.40     -11.95  -16.52
36            Power Generation/Distribution     153.00      -4.25   -2.70
37           Oil Exploration and Production     884.05    -133.90  -13.15
38                            Bank - Public     181.60     -28.25  -13.46
39                  Pharmaceuticals & Drugs     324.50     -40.75  -11.16
40                  Automobile - LCVS/ HVCS      66.20     -11.10  -14.36
41                             Iron & Steel     271.15     -26.60   -8.93
42                 IT Services & Consulting   1,669.70    -127.75   -7.11
43                 IT Services & Consulting     487.20     -89.15  -15.47
44                    Diamond  &  Jewellery     800.95    -103.95  -11.49
45                                   Cement   3,054.85    -519.00  -14.52
46               Pesticides & Agrochemicals     254.60     -45.55  -15.18
47                     Metals - Non Ferrous      62.65     -12.80  -16.96
48                 IT Services & Consulting     170.15      -9.05   -5.05
49                           Bank - Private      39.75      -6.10  -13.30
50    TV Broadcasting & Software Production     122.00     -22.90  -15.80

   Mkt Cap(Rs cr)
1       42,219.80
2      143,730.99
3       87,083.79
4       56,008.43
5      136,351.77
6       73,538.14
7      222,232.13
8       26,523.38
9       58,428.82
10      51,408.51
11      30,253.98
12      78,790.48
13      46,003.08
14      37,424.61
15      35,479.66
16      28,499.14
17     113,200.54
18     263,381.77
19     423,062.97
20      32,277.88
21      19,744.30
22     404,756.59
23     183,818.69
24      23,334.01
25     224,204.38
26      76,019.33
27     189,669.13
28      34,904.66
29     210,036.63
30     101,648.80
31      36,475.27
32     127,488.36
33     124,806.77
34      75,594.42
35      75,984.89
36      80,043.32
37     560,422.94
38     162,070.95
39      77,858.42
40      20,449.00
41      30,544.77
42     626,535.67
43      48,053.93
44      71,107.23
45      88,170.14
46      19,452.60
47      23,288.24
48      97,212.78
49      49,888.13
50      11,717.90
================================================================

=========================================================

                                         Company Name  \
1   Adani Ports\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\...
2   Asian Paints\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t...
3   Axis Bank\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\...
4   Bajaj Auto\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t...
5   Bajaj Finance\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\...
6   Bajaj Finserv\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\...
7   Bharti Airtel\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\...
8   Bharti Infratel\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\...
9   BPCL\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t...
10  Britannia\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\...
11  Cipla\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\...
12  Coal India\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t...
13  Dr Reddys Labs\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t...
14  Eicher Motors\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\...
15  GAIL\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t...
16  Grasim\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t...
17  HCL Tech\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t...
18  HDFC\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t...
19  HDFC Bank\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\...
20  Hero Motocorp\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\...
21  Hindalco\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t...
22  HUL\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\...
23  ICICI Bank\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t...
24  IndusInd Bank\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\...
25  Infosys\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\...
26  IOC\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\...
27  ITC\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\...
28  JSW Steel\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\...
29  Kotak Mahindra\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t...
30  Larsen\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t...
31  M&M\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\...
32  Maruti Suzuki\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\...
33  Nestle\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t...
34  NTPC\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t...
35  ONGC\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t...
36  Power Grid Corp\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\...
37  Reliance\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t...
38  SBI\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\...
39  Sun Pharma\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t...
40  Tata Motors\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\...
41  Tata Steel\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t...
42  TCS\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\...
43  Tech Mahindra\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\...
44  Titan Company\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\...
45  UltraTechCement\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\...
46  UPL\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\t\...
47  Vedanta\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\...
48  Wipro\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t\t\...
49  Yes Bank\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\t\t\t...
50  Zee Entertain\r\n\t\t\t\t\t\t\t\t\t\t\r\n\t\t\...

                                   Industry  LastPrice     Change    %Chg  \
1                  Transport Infrastructure     207.80     -48.60  -18.95
2                                    Paints   1,498.45    -244.50  -14.03
3                            Bank - Private     308.65    -119.50  -27.91
4               Automobile - 2 & 3 Wheelers   1,935.55    -306.75  -13.68
5                            Finance - NBFC   2,266.15    -685.75  -23.23
6                      Finance - Investment   4,621.05  -1,612.00  -25.86
7      Telecommunication - Service Provider     407.35     -55.30  -11.95
8             Telecommunication - Equipment     143.40      -4.75   -3.21
9                                Refineries     269.35     -48.50  -15.26
10                            Consumer Food   2,137.85    -329.95  -13.37
11                  Pharmaceuticals & Drugs     375.25     -17.55   -4.47
12                                     Coal     127.85      -4.95   -3.73
13                  Pharmaceuticals & Drugs   2,768.40    -128.85   -4.45
14                  Automobile - LCVS/ HVCS  13,705.90  -1,972.55  -12.58
15                         Gas Distribution      78.00      -2.80   -3.47
16                              Diversified     433.25     -96.15  -18.16
17                 IT Services & Consulting     417.15     -27.75   -6.24
18                        Finance - Housing   1,520.70    -233.25  -13.30
19                           Bank - Private     771.55    -111.30  -12.61
20              Automobile - 2 & 3 Wheelers   1,616.00    -199.70  -11.00
21                             Iron & Steel      87.90     -17.60  -16.68
22            Household & Personal Products   1,869.70    -182.00   -8.87
23                           Bank - Private     284.00     -61.70  -17.85
24                           Bank - Private     336.45    -103.90  -23.59
25                 IT Services & Consulting     526.45     -58.75  -10.04
26                               Refineries      80.75      -9.85  -10.87
27                       Cigarettes/Tobacco     154.30     -21.20  -12.08
28                             Iron & Steel     144.40     -31.35  -17.84
29                           Bank - Private   1,098.25    -164.10  -13.00
30               Engineering & Construction     724.05    -140.65  -16.27
31  Automobile - Auto & Truck Manufacturers     293.40     -29.20   -9.05
32              Automobile - Passenger Cars   4,220.35    -858.85  -16.91
33                            Consumer Food  12,944.65  -1,200.85   -8.49
34            Power Generation/Distribution      76.40      -4.85   -5.97
35           Oil Exploration and Production      60.40     -11.95  -16.52
36            Power Generation/Distribution     153.00      -4.25   -2.70
37           Oil Exploration and Production     884.05    -133.90  -13.15
38                            Bank - Public     181.60     -28.25  -13.46
39                  Pharmaceuticals & Drugs     324.50     -40.75  -11.16
40                  Automobile - LCVS/ HVCS      66.20     -11.10  -14.36
41                             Iron & Steel     271.15     -26.60   -8.93
42                 IT Services & Consulting   1,669.70    -127.75   -7.11
43                 IT Services & Consulting     487.20     -89.15  -15.47
44                    Diamond  &  Jewellery     800.95    -103.95  -11.49
45                                   Cement   3,054.85    -519.00  -14.52
46               Pesticides & Agrochemicals     254.60     -45.55  -15.18
47                     Metals - Non Ferrous      62.65     -12.80  -16.96
48                 IT Services & Consulting     170.15      -9.05   -5.05
49                           Bank - Private      39.75      -6.10  -13.30
50    TV Broadcasting & Software Production     122.00     -22.90  -15.80

   Mkt Cap(Rs cr)
1       42,219.80
2      143,730.99
3       87,083.79
4       56,008.43
5      136,351.77
6       73,538.14
7      222,232.13
8       26,523.38
9       58,428.82
10      51,408.51
11      30,253.98
12      78,790.48
13      46,003.08
14      37,424.61
15      35,479.66
16      28,499.14
17     113,200.54
18     263,381.77
19     423,062.97
20      32,277.88
21      19,744.30
22     404,756.59
23     183,818.69
24      23,334.01
25     224,204.38
26      76,019.33
27     189,669.13
28      34,904.66
29     210,036.63
30     101,648.80
31      36,475.27
32     127,488.36
33     124,806.77
34      75,594.42
35      75,984.89
36      80,043.32
37     560,422.94
38     162,070.95
39      77,858.42
40      20,449.00
41      30,544.77
42     626,535.67
43      48,053.93
44      71,107.23
45      88,170.14
46      19,452.60
47      23,288.24
48      97,212.78
49      49,888.13
50      11,717.90

In [14]:
#function that alerts if a % change is over a given threshold in a 2 minute period
def change_alert(threshold):
    data1 = stock_data()
    a1 = [float(s) for s in data1[["%Chg"]].values]
    a1 = np.asarray(a1)
    
    sleep(120)
    
    data2 = stock_data()
    a2 = [float(s) for s in data2[["%Chg"]].values]
    a2 = np.asarray(a2)
    
    i=0
    for i in range(len(a2)):
        diff = a2[i] - a1[i]
        count = 0
        if abs(diff)>=threshold:
            count +=1
            if diff>0:
                print("\nAlert: Company %s has gone down!", data2["Company Name"][index[i]])
            else:
                print("\nAlert: Company %s has gone up!", data2["Company Name"][index[i]])
    if count == 0:
        print("Everything is fine. No market fluctuation.")

In [15]:
#Call function to alert if %Chg fluctuates by 2%
change_alert(2)

Everything is fine. No market fluctuation.

In [10]:
#Using stockstats indicators
import stockstats as st

In [11]:
#Use Last price at the beginning as Open, and Close at the end of each time instance
data1 = stock_data()
#sleep for two minutes
sleep(120)
data2 = stock_data()

data = data1['LastPrice'].copy()
data = pd.DataFrame(data)
data.columns = ['open']
close = data2['LastPrice'].copy()
data['close'] = close

In [12]:
data.head()

       open     close
1    231.75    231.75
2  1,524.85  1,524.85
3    303.15    303.15
4  1,937.15  1,937.15
5  2,474.20  2,474.20

In [13]:
#trying to pass zero values for other columns
emptylist = [0] * len(data)
data['high'] = emptylist
data['low'] = emptylist
data['volume'] = emptylist
data['amount'] = emptylist

In [16]:
stock = st.StockDataFrame.retype(data)

In [17]:
stock.head()

       open     close  high  low  volume  amount
1    231.75    231.75     0    0       0       0
2  1,524.85  1,524.85     0    0       0       0
3    303.15    303.15     0    0       0       0
4  1,937.15  1,937.15     0    0       0       0
5  2,474.20  2,474.20     0    0       0       0

In [ ]:
stock.get('change')

In [ ]:
stock.get('macd')